apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-mariadb-eks-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-mariadb-eks-boilerplate
  template:
    metadata:
      labels:
        app: nestjs-mariadb-eks-boilerplate
    spec:
      containers:
        - name: nestjs-mariadb-eks-boilerplate
          image: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/nestjs-mariadb-eks-boilerplate:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
