apiVersion: v1
kind: Service
metadata:
  name: nestjs-mariadb-eks-boilerplate-service
spec:
  selector:
    app: nestjs-mariadb-eks-boilerplate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
